### ISSUE TITLE
fixtureで本のデータを追加する

### ISSUE THREAD

**Issue by dsk52** [dsk52/sandbox-node#4]
typeorm-fixtures-cli を入れてあるので、fixtureを使ってテスト用データが4,5件入るようにする

**Comment by dsk52** [comment]
fixture はこういう感じで入れようとしてる

```yml
entity: Book
items:
  comment{1..4}:
    id:
    title: "本のタイトル($current)"
    publish_date: "2021-10-05 00:00:00"
```

id は autoincrement を期待してあけてある

datetime なpublish_dateなカラムに対してのデータ追加でコケる


```
:
`publish_date` datetime NOT NULL,
:
```

エラー文の一部を抜粋したものが以下

```
Fail fixture loading: ER_NO_DEFAULT_FOR_FIELD: Field 'publish_date' doesn't have a default value
QueryFailedError: ER_NO_DEFAULT_FOR_FIELD: Field 'publish_date' doesn't have a default value
:

    code: 'ER_NO_DEFAULT_FOR_FIELD',
    errno: 1364,
    sqlMessage: "Field 'publish_date' doesn't have a default value",
    sqlState: 'HY000',
    index: 0,
    sql: "INSERT INTO `book`(`id`, `title`, `publish_date`) VALUES (NULL, '本のタイトル1', DEFAULT)"
  },
```

id部分はあけてるのでNULLはいいし、タイトルについては認識してるのでOK
datetime部分がDEFAULTになってしまって認識されてない感じ
